name: Workflow
run-name: Workflow triggered by @${{ github.actor }}

on:
  pull_request:
    types: [opened, reopened]

env:
  GITHUB_ACTIONS: "true"

jobs:
  github-task-job:
    runs-on: ubuntu-latest

    steps:
      - name: Display GITHUB_ACTIONS env variable
        run: echo "The value of GITHUB_ACTIONS is $GITHUB_ACTIONS"

      - name: Show branch and repository names
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.head_ref }}"

      - name: Show triggering event
        run: echo "This workflow was triggered by the event -> ${{ github.event_name }}"
